server:
  port: 8080

spring:
  profiles:
    active: mysql

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/chart
      username: sa

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/batch?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
      username: root
      password: root

      jpa:
        hibernate:
          ddl-auto: create
        properties:
          hibernate:
            format_sql: true
        show-sql: true

#  스프링 배치 메타데이터 테이블 자동 생성 설정 [Spring Boot 2.7.0 버전 이후]
  batch:
    jdbc:
      initialize-schema: always

    job:
      names: ${job.name:NONE}